framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true

    # Session configuration for CSRF protection
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # HTTP Client for Binance API
    http_client:
        scoped_clients:
            binance.client:
                base_uri: 'https://testnet.binance.vision'
                headers:
                    'Content-Type': 'application/json'
                timeout: 30

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_client:
            default_options:
                timeout: 10
