services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: trader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - php

  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: php bin/console app:trading-bot
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  adminer:
    image: adminer:5
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
