<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251016212008 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account_snapshots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, quote_balance NUMERIC(18, 8) NOT NULL, base_balance NUMERIC(18, 8) NOT NULL, total_value NUMERIC(18, 8) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE baskets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, symbol VARCHAR(20) NOT NULL, anchor_price NUMERIC(18, 8) NOT NULL, config JSON NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE bot_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(100) NOT NULL, value JSON NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D8D7AA58A90ABA9 ON bot_config (key)');
        $this->addSql('CREATE TABLE fills (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, side VARCHAR(10) NOT NULL, price NUMERIC(18, 8) NOT NULL, quantity NUMERIC(18, 8) NOT NULL, commission NUMERIC(18, 8) NOT NULL, commission_asset VARCHAR(10) NOT NULL, executed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, basket_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_fills_basket_id ON fills (basket_id)');
        $this->addSql('CREATE INDEX idx_fills_order_id ON fills (order_id)');
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exchange_order_id BIGINT DEFAULT NULL, client_order_id VARCHAR(100) NOT NULL, side VARCHAR(10) NOT NULL, type VARCHAR(30) NOT NULL, price NUMERIC(18, 8) NOT NULL, quantity NUMERIC(18, 8) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, filled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, basket_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E52FFDEEA3795DFD ON orders (client_order_id)');
        $this->addSql('CREATE INDEX idx_orders_basket_id ON orders (basket_id)');
        $this->addSql('CREATE INDEX idx_orders_client_order_id ON orders (client_order_id)');
        $this->addSql('CREATE INDEX idx_orders_status ON orders (status)');
        $this->addSql('ALTER TABLE fills ADD CONSTRAINT FK_D7F7FB108D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fills ADD CONSTRAINT FK_D7F7FB101BE1FB52 FOREIGN KEY (basket_id) REFERENCES baskets (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE1BE1FB52 FOREIGN KEY (basket_id) REFERENCES baskets (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fills DROP CONSTRAINT FK_D7F7FB108D9F6D38');
        $this->addSql('ALTER TABLE fills DROP CONSTRAINT FK_D7F7FB101BE1FB52');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE1BE1FB52');
        $this->addSql('DROP TABLE account_snapshots');
        $this->addSql('DROP TABLE baskets');
        $this->addSql('DROP TABLE bot_config');
        $this->addSql('DROP TABLE fills');
        $this->addSql('DROP TABLE orders');
    }
}
